name: backend_ci_test

on:
  pull_request:
    branches:
      - main
    workflow_dispatch:

jobs:
  backend_ci_test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    permissions:
      contents: read
      pull-requests: write
      checks: write

    steps:
      - uses: actions/checkout@v3

      - name: Setup ASP.NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 9.0

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore
      
      - name: Run Tests with Coverage
        run: |
          dotnet test --no-restore \
            --logger "trx;LogFileName=test-results.trx" \
            /p:CollectCoverage=true \
            /p:CoverletOutputFormat=cobertura \
            /p:CoverletOutput=./coverage.cobertura.xml \
            /p:ExcludeByFile="**/Migrations/*"

      - name: Find coverage output path
        run: |
          coverage_file=$(find . -name "coverage.cobertura.xml" | head -n 1)
          cp "$coverage_file" .
        
      - name: Code Coverage Report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: ./coverage.cobertura.xml
          badge: true
          fail_below_min: true
          format: markdown
          hide_branch_rate: false
          hide_complexity: false
          indicators: true
          output: both
          thresholds: "50 50"
      
      - name: Post Coverage Comment to PR
        uses: marocchino/sticky-pull-request-comment@v2
        if: github.event_name == 'pull_request'
        with:
          recreate: true
          path: code-coverage-results.md
        
      - name: Report Tests
        uses: dorny/test-reporter@v2
        if: always()
        with:
          name: DotNET Tests
          path: "**/test-results.trx"
          reporter: dotnet-trx
          fail-on-error: true